---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bbex-ping-ols-01-config
  namespace: monitoring
data:
  config.yml: |
    #modules:
    #  icmp:
    #    prober: icmp
    #    timeout: 15s
    #    icmp:
    #      preferred_ip_protocol: "ip4"
    #      ttl: 255
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          preferred_ip_protocol: "ip4" # tried "ip6"
      icmp:
        prober: icmp
        timeout: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbex-ping-ols-01-config
  namespace: monitoring
  labels:
    app: bbex-ping-ols-01-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbex-ping-ols-01-config
  template:
    metadata:
      labels:
        app: bbex-ping-ols-01-config
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        args:
          - "--config.file=/etc/blackbox-exporter/config.yml"
        ports:
        - containerPort: 9115
        securityContext:
          #runAsUser: 0  # รันด้วยสิทธิ์ root
          #runAsGroup: 0  
          #allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_RAW  
        volumeMounts:
        - name: config-volume
          mountPath: /etc/blackbox-exporter
      volumes:
      - name: config-volume
        configMap:
          name: bbex-ping-ols-01-config
---
apiVersion: v1
kind: Service
metadata:
  name: bbex-ping-ols-01-config
  namespace: monitoring
spec:
  selector:
    app: bbex-ping-ols-01-config
  type: NodePort
  ports:
    - port: 9115
      targetPort: 9115
      nodePort: 30611
